// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

interface IRoleManager {
    error AlreadyDeployed( address _vault );
    event AddedNewVault( address indexed vault,address indexed debtAllocator,uint256 category ) ;
    event GovernanceTransferred( address indexed previousGovernance,address indexed newGovernance ) ;
    event RemovedVault( address indexed vault ) ;
    event UpdateDebtAllocator( address indexed vault,address indexed debtAllocator ) ;
    event UpdateDefaultProfitMaxUnlock( uint256 newDefaultProfitMaxUnlock ) ;
    event UpdatePendingGovernance( address indexed newPendingGovernance ) ;
    event UpdatePositionHolder( bytes32 indexed position,address indexed newAddress ) ;
    event UpdatePositionRoles( bytes32 indexed position,uint256 newRoles ) ;
    function ACCOUNTANT(  ) external view returns (bytes32 ) ;
    function ALLOCATOR_FACTORY(  ) external view returns (bytes32 ) ;
    function BRAIN(  ) external view returns (bytes32 ) ;
    function DADDY(  ) external view returns (bytes32 ) ;
    function DEBT_ALLOCATOR(  ) external view returns (bytes32 ) ;
    function KEEPER(  ) external view returns (bytes32 ) ;
    function REGISTRY(  ) external view returns (bytes32 ) ;
    function SECURITY(  ) external view returns (bytes32 ) ;
    function STRATEGY_MANAGER(  ) external view returns (bytes32 ) ;
    function acceptGovernance(  ) external   ;
    function addNewVault( address _vault,uint256 _category,address _debtAllocator ) external   ;
    function addNewVault( address _vault,uint256 _category ) external   ;
    function chad(  ) external view returns (address ) ;
    function defaultProfitMaxUnlock(  ) external view returns (uint256 ) ;
    function getAccountant(  ) external view returns (address ) ;
    function getAllVaults(  ) external view returns (address[] memory ) ;
    function getAllocatorFactory(  ) external view returns (address ) ;
    function getBrain(  ) external view returns (address ) ;
    function getBrainRoles(  ) external view returns (uint256 ) ;
    function getCategory( address _vault ) external view returns (uint256 ) ;
    function getDaddy(  ) external view returns (address ) ;
    function getDaddyRoles(  ) external view returns (uint256 ) ;
    function getDebtAllocator( address _vault ) external view returns (address ) ;
    function getDebtAllocator(  ) external view returns (address ) ;
    function getDebtAllocatorRoles(  ) external view returns (uint256 ) ;
    function getKeeper(  ) external view returns (address ) ;
    function getKeeperRoles(  ) external view returns (uint256 ) ;
    function getPosition( bytes32 _positionId ) external view returns (address , uint256 ) ;
    function getPositionHolder( bytes32 _positionId ) external view returns (address ) ;
    function getPositionRoles( bytes32 _positionId ) external view returns (uint256 ) ;
    function getRegistry(  ) external view returns (address ) ;
    function getSecurity(  ) external view returns (address ) ;
    function getSecurityRoles(  ) external view returns (uint256 ) ;
    function getStrategyManager(  ) external view returns (address ) ;
    function getStrategyManagerRoles(  ) external view returns (uint256 ) ;
    function getVault( address _asset,string memory _apiVersion,uint256 _category ) external view returns (address ) ;
    function governance(  ) external view returns (address ) ;
    function isVaultsRoleManager( address _vault ) external view returns (bool ) ;
    function name(  ) external view returns (string memory ) ;
    function newVault( address _asset,uint256 _category ) external  returns (address ) ;
    function newVault( address _asset,uint256 _category,uint256 _depositLimit,uint256 _profitMaxUnlockTime ) external  returns (address ) ;
    function newVault( address _asset,uint256 _category,uint256 _depositLimit ) external  returns (address ) ;
    function pendingGovernance(  ) external view returns (address ) ;
    function removeRoles( address[] memory _vaults,address _holder,uint256 _role ) external   ;
    function removeVault( address _vault ) external   ;
    function setDefaultProfitMaxUnlock( uint256 _newDefaultProfitMaxUnlock ) external   ;
    function setPositionHolder( bytes32 _position,address _newHolder ) external   ;
    function setPositionRoles( bytes32 _position,uint256 _newRoles ) external   ;
    function transferGovernance( address _newGovernance ) external   ;
    function updateDebtAllocator( address _vault,address _debtAllocator ) external   ;
    function updateDebtAllocator( address _vault ) external  returns (address _newDebtAllocator) ;
    function updateKeeper( address _vault,address _keeper ) external   ;
    function vaultConfig( address  ) external view returns (address asset, uint256 category, address debtAllocator, uint256 index) ;
    function vaults( uint256  ) external view returns (address ) ;
}